### PR TITLE
Close dropdown and add message on switch teams

### PR DESCRIPTION
**Pull request by joecohens**

### CODE REVIEW

**Comment by rdev** [comment]
Closing the dropdown is a good idea, but I don't think message is necessary. There's already plenty of visual feedback and flashing the whole header looks a little weird IMO
Generally I try to follow the way [zeit.co](https://zeit.co) works, and it doesn't really do anything like that

**Comment by joecohens** [comment]
Well, they do it on `now-desktop` not showing the message makes it feel odd since it takes a split of a second to reload the data. If you don't like it I can remove it.

**Comment by rdev** [comment]
Yeah, let's remove it. The message in now-desktop is about the CLI, which works in that context.

Actually now that I think about it, we can probably ease the transition via "loading" placeholder on main views similar to how it's implemented on new Deployment Details

**Comment by joecohens** [comment]
👍

**Comment by rdev** [comment]
We shouldn't hide the entire UI while the switch is happening. I was thinking about something like a loader inside the views themselves:
screen shot 2018-08-15 at 17 21 00

But this looks weird with 2 logos being on screen at the same time.

Actually, I think we can do this visual feedback a lot simpler if we just set `context.refreshing` when team switch is in progress. This will automatically show `FlatList`'s loading indicator which is good enough to show the user that something's loading

**Comment by joecohens** [comment]
I've updated it so we use the setRefresh, it looks ok :)

**Comment by rdev** [comment]
Thanks! Looks good 👍

**Comment by joecohens** [comment]
🍻

**Pull request merged**
