### PR TITLE
Release v1.2.0

### PR DESCRIPTION
**Pull request by rdev**
This is a PR for the next major update `1.2.0` that will go through the stores.

## v1.2.0 TODO

- [ ] Properly handle unauthenticated state in Today widgets (#19)
- [ ] Cache latest state and display it on startup (#18). This will also make sure user is never stuck on splash screen in case of a network failure
- [ ] Refactor Settings screen (#12)
- [ ] Properly handle empty avatars (#30 / #16)
- [ ] Delete deployments
- [ ] An option to buy domain during aliasing. It appears according to [3.1.5 (a)](https://developer.apple.com/app-store/review/guidelines/#multiplatform-services) of Apple Review Guidelines that domain purchase should not trigger a rejection for not using iAP
- [ ] Scale management for deployments. Currently we display scale table in deployment details view but it'll be nice to have the ability to set scale rules from the phone directly
- [ ] Deploy stuff via the app using share extensions. This also needs to have an ability to set environment variables like [deploy.now.sh](https://deploy.now.sh) does
- [ ] [?] Should we also prompt aliasing after deployment is done?
- [ ] Fix background fetch on the Watch sometimes loosing usage which leads to a stale complication
- [ ] With iOS 12 right around the corner, support for Siri Shortcuts for accessing deployments and usage would be nice

### CODE REVIEW

**Comment by MAPESO** [comment]
@rdev Dark mode 😢 💔

**Comment by MAPESO** [comment]
I understand `iOS` that you will have a dark mode, but Android users do not have that option. let me know how I can help you to implement the dark mode in android ❤️ 

Have a nice day 😸

**Comment by rdev** [comment]
@MAPESO I have thought about dark mode and it'll certainly be cool to have, but probably after this release. With the way everything is set up currently, dark mode will be quite a bit of a hassle and this release already has a lot planned.

Also now that I think about it, nothing else across ZEIT has dark mode. If https://github.com/zeit/now-desktop/issues/485 happens, then we should think about it here.

Also also since ZEIT has been slashing dark everything lately, I'm curious what @evilrabbit thinks about this

**Comment by rdev** [comment]
Closing this in favor of an upcoming v2 rewrite

**Pull request closed without merging**
